Dudas:

* Ejercicio 4: que sería el indice booleano? Una mascara? Como seria la resolución del ejercicio?

* Ejercicio 8: no entendemos la consigna. Que son los escalares?

* Ejercicio 11: que es una matriz de dimension 5,5,3?

In [2]:
import numpy as np

1-Crea un objeto ndarray con elementos del 10 al 50.
Ejemplo:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

4-Utiliza el índice booleano para generar los resultados del candidato C dados los siguientes datos:
-Nombres de los candidatos: candidatoA, candidatoB, candidatoC, candidatoD. 
-Votos de los candidatos en las mesas A1, B1 y C1 =
Candidato A =
* Mesa A1 = 10.1
* Mesa B1 = 5.4
* Mesa C1 = 21.2
* Candidato B =
* Mesa A1 = 33.1
* Mesa B1 = 40.2
* Mesa C1 = 33.7
* Candidato C =
* Mesa A1 = 33.1
* Mesa B1 = 40.2
* Mesa C1 = 33.7
* Candidato D =
* Mesa A1 = 50.1
* Mesa B1 = 40.5
* Mesa C1 = 30.1

In [3]:
resultados = np.array([
                # A    B     C       D
                [10.1, 33.1, 33.1, 50.1], # A1
                [5.4,  40.2, 40.2, 40.5],   # B1
                [21.2, 33.7, 33.7, 30.1]    # C1
])

In [16]:
cand_c = np.array([ 
    [False,False,True,False],
    [False,False,True,False],
    [False,False,True,False]
                  ])

In [15]:
resultados[cand_c]

array([33.1, 40.2, 33.7])

5-Crear una matriz de 4x4 con valores que van de 0 a 15.

In [23]:
array1 = np.arange(0,16).reshape(4,4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

6- Crear una matriz de 5x5 con el valor 1 en todos sus bordes y 0 en su interior.

In [40]:
array = np.ones((5,5))
array[1:4,1:4] = 0
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
arr15=np.random.randint(0,1,25).reshape(5,5)

for fila in range(0,5):
    for columna in range (0,5):
        print(arr15[fila,columna])
        if fila==0:
            arr15[fila,columna] =1
        if fila==4:    
            arr15[fila,columna] =1
        if columna== 0:
            arr15[fila,columna]=1
        if columna==4:
            arr15[fila,columna]=1
        
print(arr15)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


7-Crea una matriz de 5x5 con los valores 1,2,3,4 justo debajo de la diagonal.
Ejemplo: 
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

In [58]:
arr5= np.diag([0,1,2,3,4,0])
arr5[0:5,1:]

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

8-Imprima el valor mínimo y máximo representable para cada tipo escalar en Numpy.


9-Dado un array de dos dimensiones, mostrar si este tiene un valor nAn.


In [59]:
arr8 =np.array ([[1,2,3],[3,np.nan,5]])
np.isnan(arr8).any()

True

10-Encontrar el valor más cercano de un valor dado en una matriz.

In [119]:
array = np.random.randint(1, 15, 10)
dicc = {}

for i in array:
    valor = 7
    cercania = abs(i-valor)
    
    dicc[cercania] = i
    
dicc[min(dicc.keys())]

8

In [129]:
arr9 = np.random.uniform(1,20,10) #le indicamos que nos genera n° entre 1 y 20, una cantidad de 10
print(arr9)
valor = 5    #asignamos un valor aleatorio

#ahora en el array generado buscamos el valor mas cercano a 5
arr9.flat[np.abs(arr9 - valor).argmin()]

[18.37002854  4.61198926  9.16018234  4.43793783 19.78015922 19.09373734
  8.52617049  3.7929518   9.38511699 17.77630602]


4.611989258182088

In [142]:
indice_del_menor = np.abs(arr9 - valor).argmin()

In [143]:
arr9.flat[indice_del_menor]

4.611989258182088

11-Considerando una matriz de dimensión (5,5,3),multiplicarla por una matriz con dimensiones(5,5).

In [1]:
import numpy as np

In [3]:
np.ones((5,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

12-Tomando el vector [1, 2, 3, 4, 5], construir un nuevo vector con 3 ceros consecutivos intercalados entre cada valor.
Ejemplo: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]

In [150]:
array = np.array([1, 2, 3, 4, 5])

In [162]:
#Sumar arrays de distintas dimensiones
arr_ceros = np.zeros((3,3))

13-Encontrar el valor más frecuente en un array.

In [164]:
from scipy import stats

In [171]:
array = np.array([1, 2, 3, 4, 5, 1 , 1, 1, 2, 3, 4, 5, 5, 5, 5, 5])

In [174]:
stats.mode(array)[0][0]

5

14 - Obtener los n valores más grandes de una matriz.

In [230]:
array = np.array([
    [2, 0, 5, 0, 0],
    [1, 0, 0, 7, 0],
    [0, 2, 6, 5, 15],
    [0, 0, 3, 16, 12],
    [0, 0, 0, 4, 0]
])

In [211]:
array = np.sort(array.flatten())

In [224]:
array[-5:]

array([ 6,  7, 12, 15, 16])

15 - Tomando una matriz de 10x3, extraer las filas con valores desiguales y mostrarlas por pantalla.

In [239]:
array = np.random.randint(1, 50, 30).reshape(10,3)

In [243]:
array

array([[41,  1, 23],
       [46,  5,  4],
       [41, 22, 47],
       [35, 39,  7],
       [23, 48, 35],
       [14, 29,  1],
       [44, 24, 33],
       [ 8, 15,  5],
       [ 6, 47, 48],
       [ 2, 19,  2]])

In [248]:
array[0]

array([41,  1, 23])

In [ ]:
(array[i][0] == array[i][1]) & (array[i][1] == array[i][2])